/*Copyright (c) 2015-2016 wavemaker-com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker-com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker-com*/
package com.wavemakersample.d2p0fohnal0nue.dao;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.orm.hibernate4.HibernateTemplate;
import org.springframework.stereotype.Repository;

import com.wavemaker.runtime.data.dao.WMGenericDaoImpl;

import com.wavemakersample.d2p0fohnal0nue.Pgemployee;

/**
 * Specifies methods used to obtain and modify Pgemployee related information
 * which is stored in the database.
 */
@Repository("d2p0fohnal0nue.PgemployeeDao")
public class PgemployeeDao extends WMGenericDaoImpl<Pgemployee, Integer> {

    @Autowired
    @Qualifier("d2p0fohnal0nueTemplate")
    private HibernateTemplate template;

    public HibernateTemplate getTemplate() {
        return this.template;
    }
}

