/*Copyright (c) 2015-2016 wavemaker-com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker-com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker-com*/
package com.wavemakersample.d2p0fohnal0nue.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

import com.wavemaker.runtime.data.exception.EntityNotFoundException;
import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.file.model.Downloadable;

import com.wavemakersample.d2p0fohnal0nue.Pgemployee;

/**
 * Service object for domain model class {@link Pgemployee}.
 */
public interface PgemployeeService {

    /**
     * Creates a new Pgemployee. It does cascade insert for all the children in a single transaction.
     *
     * This method overrides the input field values using Server side or database managed properties defined on Pgemployee if any.
     *
     * @param pgemployee Details of the Pgemployee to be created; value cannot be null.
     * @return The newly created Pgemployee.
     */
	Pgemployee create(Pgemployee pgemployee);


	/**
	 * Returns Pgemployee by given id if exists.
	 *
	 * @param pgemployeeId The id of the Pgemployee to get; value cannot be null.
	 * @return Pgemployee associated with the given pgemployeeId.
     * @throws EntityNotFoundException If no Pgemployee is found.
	 */
	Pgemployee getById(Integer pgemployeeId) throws EntityNotFoundException;

    /**
	 * Find and return the Pgemployee by given id if exists, returns null otherwise.
	 *
	 * @param pgemployeeId The id of the Pgemployee to get; value cannot be null.
	 * @return Pgemployee associated with the given pgemployeeId.
	 */
	Pgemployee findById(Integer pgemployeeId);


	/**
	 * Updates the details of an existing Pgemployee. It replaces all fields of the existing Pgemployee with the given pgemployee.
	 *
     * This method overrides the input field values using Server side or database managed properties defined on Pgemployee if any.
     *
	 * @param pgemployee The details of the Pgemployee to be updated; value cannot be null.
	 * @return The updated Pgemployee.
	 * @throws EntityNotFoundException if no Pgemployee is found with given input.
	 */
	Pgemployee update(Pgemployee pgemployee) throws EntityNotFoundException;

    /**
	 * Deletes an existing Pgemployee with the given id.
	 *
	 * @param pgemployeeId The id of the Pgemployee to be deleted; value cannot be null.
	 * @return The deleted Pgemployee.
	 * @throws EntityNotFoundException if no Pgemployee found with the given id.
	 */
	Pgemployee delete(Integer pgemployeeId) throws EntityNotFoundException;

	/**
	 * Find all Pgemployees matching the given QueryFilter(s).
     * All the QueryFilter(s) are ANDed to filter the results.
     * This method returns Paginated results.
	 *
     * @deprecated Use {@link #findAll(String, Pageable)} instead.
	 *
     * @param queryFilters Array of queryFilters to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null returns all matching records.
     * @return Paginated list of matching Pgemployees.
     *
     * @see QueryFilter
     * @see Pageable
     * @see Page
	 */
    @Deprecated
	Page<Pgemployee> findAll(QueryFilter[] queryFilters, Pageable pageable);

    /**
	 * Find all Pgemployees matching the given input query. This method returns Paginated results.
     * Note: Go through the documentation for <u>query</u> syntax.
	 *
     * @param query The query to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null returns all matching records.
     * @return Paginated list of matching Pgemployees.
     *
     * @see Pageable
     * @see Page
	 */
    Page<Pgemployee> findAll(String query, Pageable pageable);

    /**
	 * Exports all Pgemployees matching the given input query to the given exportType format.
     * Note: Go through the documentation for <u>query</u> syntax.
	 *
     * @param exportType The format in which to export the data; value cannot be null.
     * @param query The query to filter the results; No filters applied if the input is null/empty.
     * @param pageable Details of the pagination information along with the sorting options. If null exports all matching records.
     * @return The Downloadable file in given export type.
     *
     * @see Pageable
     * @see ExportType
     * @see Downloadable
	 */
    Downloadable export(ExportType exportType, String query, Pageable pageable);

	/**
	 * Retrieve the count of the Pgemployees in the repository with matching query.
     * Note: Go through the documentation for <u>query</u> syntax.
     *
     * @param query query to filter results. No filters applied if the input is null/empty.
	 * @return The count of the Pgemployee.
	 */
	long count(String query);


}

